trigger:
 branches:
   include:
     - main

pool: B17_AgentPool

stages:
# =========================
# VALIDATE STAGE 
# =========================
  - stage: Validation
    displayName: "Terraform Validation Stage"
    jobs:
      - job: TerraformValidate
        displayName: "Terraform Validate"
        steps:
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'sanjay_sc'
              backendAzureRmStorageAccountName: 'sanjaystg'
              backendAzureRmContainerName: 'sancontainer'
              backendAzureRmKey: 'tf/terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
# =========================
# SECUIRTY STAGE 
# =========================
  - stage: Scan
    displayName: "Scanning Stage"
    dependsOn: Validation
    jobs:
      - job: CodeScan
        displayName: "Terraform Secuirty Scan"
        steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                pip install checkov
                checkov -d .